name: Failure Pipeline #2

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  docker-failure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trigger Docker image failure
        run: |
          echo "Starting Docker build..."
          docker pull python:this-tag-does-not-exist